# Generated by Django 5.0.14 on 2026-08-12 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('x', 'X')], max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('platform_post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='campaigns.campaign')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scheduledpost',
            constraint=models.UniqueConstraint(fields=('campaign', 'platform'), name='unique_scheduled_post_per_campaign_platform'),
        ),
    ]
