# Generated by Django 5.0.14 on 2026-08-12 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('signature_valid', models.BooleanField()),
                ('raw_payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='scheduling.scheduledpost')),
            ],
        ),
    ]
