# Generated by Django 5.0.14 on 2026-08-12 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('x', 'X')], max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64)),
                ('caption', models.TextField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('published', 'Published'), ('failed', 'Failed')], default='accepted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='fakepost',
            constraint=models.UniqueConstraint(fields=('platform', 'idempotency_key'), name='unique_fake_post_per_platform_key'),
        ),
    ]
