# Generated by Django 5.0.14 on 2026-08-12 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('x', 'X')], max_length=20)),
                ('image', models.ImageField(upload_to='platform_variants/')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_assets', to='campaigns.campaign')),
            ],
        ),
        migrations.AddConstraint(
            model_name='platformasset',
            constraint=models.UniqueConstraint(fields=('campaign', 'platform'), name='unique_asset_per_campaign_platform'),
        ),
    ]
